### ISSUE TITLE
Clarification on doing api testing through browser(chai-http)

### ISSUE THREAD

**Issue by keyjm** [BigstickCarpet/super-powered-api-testing#2]
Hello, Our QA team is trying to use the chai-http library based on example you provided specifically for using this to test through browser. It seems like to test against the browser (by doing npm start) the api needs to be on local machine. How do we do api test through browser if the api is living on diff environments (QA,stg etc)?

**Comment by BigstickCarpet** [comment]
This project is just for demo purposes, so I kept it as simple as possible by just using `localhost`, but you can write your tests to call any HTTP server that you want.

```javascript
chai.request('http://some-server.com')
  .get('/users')
  .then(function (res) {
     expect(res).to.have.status(200);
  });
```

**Comment by kunalmalviya** [comment]
Ok...how do we test this in browser? Do we create a seperate html file for that and inject script and dependencies?

**Comment by BigstickCarpet** [comment]
Yes, running tests in the browser requires an HTML page with `<script>` tags.  You can create this page manually, like I did in [this example](https://github.com/BigstickCarpet/super-powered-api-testing/blob/master/tests/chai-http/browser.html), or you can use a test runner, such as [Karma](https://karma-runner.github.io/1.0/index.html), [Nightwatch](http://nightwatchjs.org/), [Selenium](http://www.seleniumhq.org/), [Zuul](https://github.com/defunctzombie/zuul), etc.
